# Bigger volume steps with arrow keys (very popular change)
UP           add volume 5
DOWN         add volume -5
RIGHT  seek 3
LEFT   seek -3
Ctrl+LEFT   add chapter -1
Ctrl+RIGHT  add chapter 1

Del run "trash-put" "${path}"; show-text "Deleted: ${filename}"; playlist_next force

MBTN_LEFT   cycle pause
