# Bigger volume steps with arrow keys (very popular change)
UP           add volume 5
DOWN         add volume -5
RIGHT  seek 3
LEFT   seek -3

Alt+RIGHT  seek 8
Alt+LEFT   seek -8
Ctrl+LEFT   add chapter -1
Ctrl+RIGHT  add chapter 1

Del run "trash-put" "${path}"; playlist-remove current; show-text "Deleted: ${filename}"

MBTN_LEFT   cycle pause
BS seek 0 absolute
PGUP  playlist-prev
PGDWN playlist-next

# Panning
Ctrl+l add video-pan-x -0.05
Ctrl+h add video-pan-x 0.05
Ctrl+k add video-pan-y 0.05
Ctrl+j add video-pan-y -0.05

# Zooming
Ctrl+- add video-zoom -0.1
Ctrl+= add video-zoom 0.1
