# Prefix
set -g prefix M-Space
unbind C-b
bind M-Space send-prefix

# Reload config
# bind R source-file ~/.config/tmux/tmux.conf; display-message "tmux.conf reloaded"
bind R run-shell 'tmux source-file ~/.config/tmux/tmux.conf && tmux display-message -d 600 "Config reloaded"'

set-option -g default-shell /usr/bin/zsh

# Vi mode for copy
setw -g mode-keys vi
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send -X copy-selection-and-cancel
bind a copy-mode
bind-key -T copy-mode-vi _ send-keys ^

# Pane Controls
bind-key \\ split-window -h -c "#{pane_current_path}"
bind-key - split-window -v -c "#{pane_current_path}"
bind w kill-pane

# Pane resize
bind h resize-pane -L 8
bind j resize-pane -D 8
bind k resize-pane -U 8
bind l resize-pane -R 8

# Window navigation
bind r command-prompt -I "#W" "rename-window -- '%%'"
bind t new-window -c "#{pane_current_path}"

# Active pane border
set -g pane-active-border-style "fg=#7ED4D1,bold"
set -g pane-border-style "fg=colour238"

# Copy mode selection
set -g mode-style "bg=colour141,fg=black"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'kallistoteles/tmux_status_autohide'
set -g @plugin 'pschmitt/tmux-ssh-split'


set -g @sessionx-bind 'o'
set -g @sessionx-x-path '/home/shafayet/Documents/workspace'
set -g @status_autohide_delay "3"

set-option -g @ssh-split-keep-cwd "true"
set-option -g @ssh-split-keep-remote-cwd "true"
set-option -g @ssh-split-h-key "\\"
set-option -g @ssh-split-v-key "-"

# open opencode in current directory in a popup
bind O popup -B -E -d "#{pane_current_path}" -w 90% -h 90% "/usr/bin/opencode"
bind-key F run-shell "nohup nautilus #{pane_current_path} >/dev/null 2>&1 & disown"

# General
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",*:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
set -g history-limit 50000
set -g escape-time 0
set -g focus-events on
set -g set-clipboard on
set -g allow-passthrough on
setw -g aggressive-resize on
set -g detach-on-destroy off

# Status bar
set -g status-position top
set -g status-interval 5
set -g status-left-length 30
set -g status-right-length 50
set -g window-status-separator ""
bind-key ";" run-shell "~/.config/tmux/plugins/tmux_status_autohide/autohide.tmux"

# Theme
set -g pane-active-border-style "fg=#7ED4D1,bold"
set -g pane-border-style "fg=colour238"
set -g mode-style "bg=colour141,fg=black"
set -g status-style "bg=default,fg=default"
set -g status-left "#[fg=black,bg=blue,bold] #S #[bg=default] "
set -g status-right "#[fg=blue]#{?client_prefix,PREFIX ,}#{?window_zoomed_flag,ZOOM ,}#[fg=brightblack]#h "
set -g window-status-format "#[fg=brightblack] #I:#W "
set -g window-status-current-format "#[fg=blue,bold] #I:#W "
set -g message-style "bg=default,fg=blue"
set -g message-command-style "bg=default,fg=blue"
set -g mode-style "bg=blue,fg=black"
setw -g clock-mode-colour blue

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
