[Audio]
Volume=70

[General]
ColorScheme=Breeze Dark
LastPlayedFile=file:///home/shafayet/Downloads/Video/programming/AsyncIO in Python _ Python Tutorial - Day %2396.mp4
MaxRecentFiles=50
OsdFontSize=15
PreviewThumbnailWidth=250
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true
UseSingleInstance=true

[Playback]
RestoreFilePosition=true
SeekBigStep=20
SeekMediumStep=10
SeekSmallStep=4

[Playlist]
BigFontFullscreen=false
Style=withThumbnails
