[Audio]
Volume=58
VolumeStep=2

[General]
ColorScheme=Breeze Dark
FileDialogLastLocation=file:///home/shafayet/Downloads/Video
LastPlayedFile=file:///home/shafayet/Downloads/Video/Anime/new/Shining Hearts_ Shiawase no Pan %232 English Dubbed - All Manga.mp4
LastUrl=https://www.youtube.com/watch?v=WlZHx9G1CrI&t=3132s
MaxRecentFiles=50
OsdFontSize=11
ShowHeader=false
ShowMenuBar=false
ShowPreviewThumbnail=true
UseSingleInstance=true

[Playback]
RestoreFilePosition=true
SeekBigStep=20
SeekMediumStep=10
SeekSmallStep=4

[Playlist]
BigFontFullscreen=false
PlaylistWidth=501.0625
Style=withThumbnails
