[Shortcuts]
Command_4=Alt+X
addExternalSubtitleAction=F24, Esc
audioCycleDownAction=Alt+Shift+A
audioCycleUpAction=Alt+A
loadLastPlayedFileAction=Ctrl+Return
playNextAction=PgDown
playPreviousAction=PgUp
playbackSpeedResetAction=
quitApplicationAction=Q
restartPlaybackAction=Backspace
seekBackwardBigAction=Shift+Left
seekBackwardMediumAction=Alt+Left
seekForwardBigAction=Shift+Right
seekForwardMediumAction=Alt+Right
seekNextChapterAction=Ctrl+Right
seekNextSubtitleAction=
seekPreviousChapterAction=Ctrl+Left
seekPreviousSubtitleAction=
subtitleCycleDownAction=Alt+Shift+S
subtitleCycleUpAction=Alt+S
toggleHeaderAction=
videoPanXLeftAction=Ctrl+L
videoPanXRightAction=Ctrl+H
videoPanYDownAction=Ctrl+K
videoPanYUpAction=Ctrl+J
volumeDownAction=Down
volumeUpAction=Up
zoomInAction=Ctrl+=
