# Extra autostart processes
# exec-once = uwsm-app -- my-service

# exec-once = uwsm app -- hyprsunset
# exec-once = hyprlock

workspace = 2, persistent, monitor:eDP-1
exec-once = [workspace 2] zen-browser
exec-once = [workspace 3] ghostty
exec-once = omarchy-theme-bg-next
